#
#  media add ons
#

SHELL=/bin/sh

###
###
include $(BUILDHOME)/buildprefs/make.pre
###
###

ifeq ($(MAKEDIR),1)
	INSTALL_DIR		:= $(BUILDHOME)/install/$(PLATFORM)/system/addons
endif

install: FORCE
	@$(INIT_REPORT)
	-@cd aiff && $(MAKE) $@; $(CHECK_STATUS)
	-@cd avi && $(MAKE) $@; $(CHECK_STATUS)
	-@cd quicktime && $(MAKE) $@; $(CHECK_STATUS)
	-@cd wav && $(MAKE) $@; $(CHECK_STATUS)

	@$(REPORT_STATUS)

#
# This DEFAULT target will pass along commands like "make clean" and
# "make deps"
#
.DEFAULT:
	@cd aiff && $(MAKE) $@
	@cd avi && $(MAKE) $@
	@cd quicktime && $(MAKE) $@
	@cd wav && $(MAKE) $@

# empty rule. Things that depend on this rule will always get triggered.
FORCE:
